# pre-commitの設定ファイル
repos:
  
  # blackのチェック
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [src, tests]


  # isortのチェック
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort